### ISSUE TITLE
nuxt 2.x import package to appear error

### ISSUE THREAD

**Issue by Kelvin4230** [MorevM/vue-transitions#243]
### Question

My node version is 16.10.0(npm v7.24.0). What is my missing?
<img width="1246" alt="螢幕截圖 2023-01-17 下午1 54 10" src="https://user-images.githubusercontent.com/27725227/212820499-2abbdc81-309a-4515-a717-6cbcb153b34b.png">
<img width="457" alt="螢幕截圖 2023-01-17 下午1 53 22" src="https://user-images.githubusercontent.com/27725227/212820432-42ae5d47-4378-49d2-ad34-ff8af16ea402.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/27725227/212820573-5db863b8-5592-4b55-8ff6-b6564e555c6d.png">

**Comment by MorevM** [comment]
Good day @Kelvin4230 

Thank you for discovering this, my bad.
This should be fixed in the latest release, `2.3.6`

Let me know if any errors still occur, or if everything works fine now.

**Comment by Kelvin4230** [comment]
> Good day @Kelvin4230
> 
> Thank you for discovering this, my bad. This should be fixed in the latest release, `2.3.6`
> 
> Let me know if any errors still occur, or if everything works fine now.

it's work for nuxt 2.x. thank you
