### ISSUE TITLE
TransitionExpand: no collapse transition when in bottom

### ISSUE THREAD

**Issue by reimnm** [MorevM/vue-transitions#253]
### Actual behavior

![TransitionExpand](https://github.com/MorevM/vue-transitions/assets/104208604/7790430e-74f1-4694-ad47-8a5fc63bda95)

### Expected behavior

Expand from bottom to to when element postion in bottom

### Steps to reproduce

    <header class="fixed top-0 w-full">
     <div>Content</div>
      <transition-expand>
        <div v-show="currentNavPanel"></div>
      </transition-expand>
    </footer>    
    <footer class="fixed bottom-0 w-full">
      <transition-expand>
        <div v-show="currentNavPanel"></div>
      </transition-expand>
     <div>Content</div>
    </footer>

### Environment

- Device:Desktop
- OS:Windows 11
- Browser:Chrome 116

**Comment by MorevM** [comment]
Good day @reimnm,
I can't figure out from the description what's going wrong.

The `transition-expand` smoothly increases the height of the element.
If the bottom edge of the element is fixed, the height of the element increases upwards - I see exactly that in the attached video.

Can you describe in more detail what is expected?

**Comment by MorevM** [comment]
I'll close this due to lack of feedback.
Let me know if you are still experience the issue and can explain it more clear. :)
