### ISSUE TITLE
Duplicate postinstall key in package.json

### ISSUE THREAD

**Issue by pisandelli** [MorevM/vue-transitions#265]
### Actual behavior

When trying to install the package, BUN throws this warning: 
```
warn: Duplicate key "postinstall" in object literal
   at esbuild/package.json/package.json:98:3
   ```

### Expected behavior

No warnings

### Steps to reproduce

bun install @morevm/vue-transitions

### Environment

- Device:
- OS:
- Browser:

### Possible solution

delete one of these lines (97/98) in `vue-transitions/package.json`
```
	"scripts": {
		"postinstall": "node ./scripts/postinstall.js",
		"postinstall": "node ./scripts/postinstall.js",
		...
        }

**Comment by MorevM** [comment]
Good day @pisandelli,

Thank you for noticing, sorry for the really delayed reaction.
This is fixed in just released v3.0.3. :)
