### ISSUE TITLE
[QUESTION] Tab Transition

### ISSUE THREAD

**Issue by BayBreezy** [MorevM/vue-transitions#271]
### Question

Hey @MorevM ,

For the life of me I cannot use the Slide transition to create a tab-like transition effect.

I tried different values in the `offset` prop but I cannot get it to work.

Do you know how I could get this working? Thanks in advance.

**Comment by MorevM** [comment]
Good day @BayBreezy,

Can you provide a more detailed description of what you want to do, or provide an example? 
I can imagine at least three different variations of this effect :)

**Comment by BayBreezy** [comment]
Ok. So this [Onboarder](https://ui-thing.behonbaker.com/components/dialog#onboarding) example here.

I was trying to make it slide forward and backwards like a tab.. but i gave up and settled for the fade transition LOLOL

**Comment by MorevM** [comment]
I would use a specialised slider component for this kind of animation, `vue-transitions` is not designed for this at all, it's for small interface transitions. :)

You can try something like `<transition-slide :offset="{ enter: ['-100%', 0], leave: ['100%', 0] }">` with container that has `overflow: hidden;` - this should work, but the UX still won't be the best (you need to handle the navigation backwards separately to reverse the values, I'd like to have drag/swipe support and so on)

**Comment by BayBreezy** [comment]
Yeah. The other option I was thinking about was swiperjs.

Well, I tried lol. Thanks for checking it out
